environment:
  nuget_api_key:
    secure: vxiVDKmWLJdCviOWaNdn9/GTRlDIE3nz/Al03uA5NOGrzd+7BUMrAME1g6k/Z/RR

# version format
version: 1.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2017

configuration: Release

build:
  project: src/AgodaAnalyzers.sln      # path to Visual Studio solution or project
  publish_nuget: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore src

after_build:
  - nuget pack src\Agoda.Analyzers.CodeFixes\Agoda.Analyzers.nuspec -Version %APPVEYOR_BUILD_VERSION%

artifacts:
  - path: '*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: nuget_api_key
  artifact: '*.nupkg'
  on:
    branch: master