environment:
  nuget_api_key:
    secure: kNCOsacwJ+/mYOiEhoKkrg==

# version format
version: 1.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2017

build:
  project: src/AgodaAnalyzers.sln      # path to Visual Studio solution or project
  publish_nuget: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore src

after_build:
  - nuget pack src\Agoda.Analyzers.CodeFixes\Agoda.Analyzers.nuspec -Version %version%

deploy:
- provider: NuGet
  api_key:
    secure: nuget_api_key
  artifact: 'src\Agoda.Analyzers.CodeFixes\*.nupkg'
  on:
    branch: master